// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkvnFH2Cu5A4mWJiHTnkwIHOoqbQvlUrQ',
    appId: '1:983211756132:web:6b7ae5f819abe017c3ed71',
    messagingSenderId: '983211756132',
    projectId: 'crms-bc1ee',
    authDomain: 'crms-bc1ee.firebaseapp.com',
    storageBucket: 'crms-bc1ee.firebasestorage.app',
    measurementId: 'G-5NNGPESHHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC231nnKWJs-uUFWYvYx-cSYM0rsHVNXKk',
    appId: '1:983211756132:android:6828c1c9daa273a0c3ed71',
    messagingSenderId: '983211756132',
    projectId: 'crms-bc1ee',
    storageBucket: 'crms-bc1ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGQbs4leIEmU6RcjkHVPkRxD8MqWIWUy0',
    appId: '1:983211756132:ios:85f7d37439fc9b99c3ed71',
    messagingSenderId: '983211756132',
    projectId: 'crms-bc1ee',
    storageBucket: 'crms-bc1ee.firebasestorage.app',
    iosBundleId: 'com.example.crm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGQbs4leIEmU6RcjkHVPkRxD8MqWIWUy0',
    appId: '1:983211756132:ios:85f7d37439fc9b99c3ed71',
    messagingSenderId: '983211756132',
    projectId: 'crms-bc1ee',
    storageBucket: 'crms-bc1ee.firebasestorage.app',
    iosBundleId: 'com.example.crm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkvnFH2Cu5A4mWJiHTnkwIHOoqbQvlUrQ',
    appId: '1:983211756132:web:2263a52cb205d863c3ed71',
    messagingSenderId: '983211756132',
    projectId: 'crms-bc1ee',
    authDomain: 'crms-bc1ee.firebaseapp.com',
    storageBucket: 'crms-bc1ee.firebasestorage.app',
    measurementId: 'G-P29EL6H50C',
  );
}
